[package]
name = "fast-trace"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
socket2 = "0.5"
pnet = "0.34"
anyhow = "1.0"
futures = "0.3"
ipnet = "2.9"
clap = { version = "4.4.8", features = ["derive"] }
trust-dns-resolver = { version = "0.23", features = ["tokio-runtime"] } 