codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"
  
  status:
    project:
      default:
        target: 50%
        threshold: 5%
    patch:
      default:
        target: 50%
        threshold: 10%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "**/*.rs.bk"
  - "**/tests/**"
  - "**/examples/**"
  - "**/benches/**"